language: c
compiler: gcc
sudo: required

install:
- if [ "$CC" == "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8

script:
- $CC --version
- scons
- ./mstat 14.2 42.6 13.7 51.9 12.6 44.2 98.7 10.0 31.5 23.6
