language: c
compiler: gcc
sudo: required

install:
- if [ "$CC" == "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8

script:
- $CC --version
- scons
- ./phil
